# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Thu Oct 27 02:07:50 2022
# ------------------------------------------------

package:
  name: pycosat
  version: 0.6.4
source:
  sha256: 79ffa99156810e58876dd6374af0b7bff88f9a4580ca8b8468c414c5c2454bb8
  url: https://github.com/conda/pycosat/archive/0.6.4.tar.gz
build:
  number: '1'
  script: /Users/runner/miniforge3/conda-bld/pycosat_1666836599375/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
    -m pip install . --no-deps -vv
  string: py39ha30fb19_1
requirements:
  build:
    - ca-certificates 2022.9.24 h033912b_0
    - cctools_osx-64 973.0.1 h3eff9a4_10
    - clang 14.0.4 h694c41f_0
    - clang-14 14.0.4 default_h55ffa42_0
    - clang_osx-64 14.0.4 h3a95cd4_2
    - clangxx 14.0.4 default_h55ffa42_0
    - compiler-rt 14.0.4 h7fcd477_0
    - compiler-rt_osx-64 14.0.4 h6df654d_0
    - ld64_osx-64 609 h1e06c2b_10
    - libclang-cpp14 14.0.4 default_h55ffa42_0
    - libcxx 14.0.6 hccf4f1f_0
    - libllvm13 13.0.1 h64f94b2_2
    - libllvm14 14.0.4 h41df66c_0
    - libzlib 1.2.13 hfd90126_4
    - llvm-tools 14.0.4 h41df66c_0
    - openssl 3.0.5 hfd90126_2
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
  host:
    - bzip2 1.0.8 h0d85af4_4
    - ca-certificates 2022.9.24 h033912b_0
    - libffi 3.4.2 h0d85af4_5
    - libsqlite 3.39.4 ha978bb4_0
    - libzlib 1.2.13 hfd90126_4
    - ncurses 6.3 h96cf925_1
    - openssl 3.0.5 hfd90126_2
    - pip 22.3 pyhd8ed1ab_0
    - python 3.9.13 hf8d34f4_0_cpython
    - readline 8.1.2 h3899abd_0
    - setuptools 65.5.0 pyhd8ed1ab_0
    - sqlite 3.39.4 h9ae0607_0
    - tk 8.6.12 h5dbffcc_0
    - tzdata 2022e h191b570_0
    - wheel 0.37.1 pyhd8ed1ab_0
    - xz 5.2.6 h775f41a_0
  run:
    - python >=3.9,<3.10.0a0
    - python_abi 3.9.* *_cp39
test:
  commands:
    - pip check
    - python test_package.py "0.6.4"
  files:
    - qg3-08.cnf
    - sudoku.py
    - test_package.py
    - uf20-098.cnf
  imports:
    - pycosat
  requires:
    - pip
about:
  description: 'PicoSAT is a popular SAT solver written by Armin Biere in pure C.
    This

    package provides efficient Python bindings to picosat on the C level, i.e.

    when importing pycosat, the picosat solver becomes part of the Python

    process itself.

    '
  dev_url: https://github.com/conda/pycosat
  doc_source_url: https://github.com/conda/pycosat/blob/master/README.rst
  doc_url: https://pypi.python.org/pypi/pycosat
  home: https://github.com/conda/pycosat
  license: MIT
  license_file:
    - COPYRIGHT
    - LICENSE
  summary: Bindings to picosat (a SAT solver)
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - kalefranz
    - mcg1969
    - msarahan
    - nehaljwani
    - pelson
