# This file created by conda-build 3.25.0
# ------------------------------------------------

package:
  name: zstd
  version: 1.5.2
source:
  patches: null
  sha256: f7de13462f7a82c29ab865820149e778cbfe01087b3a55b5332707abf9db4a6e
  url: https://github.com/facebook/zstd/archive/v1.5.2.tar.gz
build:
  number: 7
  run_exports:
    - zstd >=1.5.2,<1.6.0a0
  string: h829000d_7
requirements:
  build:
    - clang_bootstrap_osx-64 15.0.7 h8b24658_3
    - cmake-no-system 3.25.1 he965462_0
    - libcxx 16.0.6 hd57cbcb_0
    - make 4.3 h22f3db7_1
    - ninja 1.11.1 hb8565cd_0
  host:
    - libzlib 1.2.13 h8a1eda9_5
    - zlib 1.2.13 h8a1eda9_5
  run:
    - libzlib >=1.2.13,<1.3.0a0
test:
  commands:
    - test -f ${PREFIX}/lib/libzstd.dylib
    - test ! -f ${PREFIX}/lib/libzstd.a
    - test -f ${PREFIX}/include/zstd.h
    - zstd -be -i5
    - test -f ${PREFIX}/lib/pkgconfig/libzstd.pc
    - export PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig
    - pkg-config --cflags libzstd
    - cd cf_test
    - cmake $CMAKE_ARGS .
  files:
    - cf_test/
  requires:
    - clang_bootstrap_osx-64 15.*
    - cmake
    - pkg-config
about:
  description: 'Zstandard is a real-time compression algorithm, providing high compression

    ratios. It offers a very wide range of compression / speed trade-off, while

    being backed by a very fast decoder. It also offers a special mode for

    small data, called dictionary compression, and can create dictionaries from

    any sample set. Zstandard library is provided as open source software using

    a BSD license.

    '
  dev_url: https://github.com/facebook/zstd
  doc_url: https://facebook.github.io/zstd/zstd_manual.html
  home: http://www.zstd.net
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Zstandard - Fast real-time compression algorithm
extra:
  copy_test_source_files: true
  feedstock-name: zstd
  final: true
  recipe-maintainers:
    - hmaarrfk
    - msarahan
    - rmax
    - xhochy
