# This file created by conda-build 3.24.0
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Sat Jun 17 09:23:28 2023
# ------------------------------------------------

package:
  name: ruamel.yaml
  version: 0.17.32
source:
  sha256: ec939063761914e14542972a5cba6d33c23b0859ab6342f61cf070cfc600efc2
  url: https://pypi.io/packages/source/r/ruamel.yaml/ruamel.yaml-0.17.32.tar.gz
build:
  number: '0'
  script: /Users/runner/miniforge3/conda-bld/ruamel.yaml_1686994012442/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python
    -m pip install . --no-deps -vv
  string: py39hdc70f33_0
requirements:
  build:
    - ca-certificates 2023.5.7 h8857fd0_0
    - cctools_osx-64 973.0.1 h48a5a9d_13
    - clang 15.0.7 h694c41f_2
    - clang-15 15.0.7 default_hdb78580_2
    - clang_osx-64 15.0.7 h03d6864_3
    - clangxx 15.0.7 default_hdb78580_2
    - compiler-rt 15.0.7 he1888fc_1
    - compiler-rt_osx-64 15.0.7 he1888fc_1
    - icu 72.1 h7336db1_0
    - ld64_osx-64 609 h8ce0179_13
    - libclang-cpp15 15.0.7 default_hdb78580_2
    - libcxx 16.0.6 hd57cbcb_0
    - libiconv 1.17 hac89ed1_0
    - libllvm15 15.0.7 he4b1e75_2
    - libxml2 2.11.4 hd95e348_0
    - libzlib 1.2.13 h8a1eda9_5
    - llvm-tools 15.0.7 he4b1e75_2
    - openssl 3.1.1 h8a1eda9_1
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.2 hbc0c0cd_6
  host:
    - bzip2 1.0.8 h0d85af4_4
    - ca-certificates 2023.5.7 h8857fd0_0
    - libffi 3.4.2 h0d85af4_5
    - libsqlite 3.42.0 h58db7d2_0
    - libzlib 1.2.13 h8a1eda9_5
    - ncurses 6.4 hf0c8a7f_0
    - openssl 3.1.1 h8a1eda9_1
    - pip 23.1.2 pyhd8ed1ab_0
    - python 3.9.16 h709bd14_0_cpython
    - python_abi 3.9 3_cp39
    - readline 8.2 h9e318b2_1
    - ruamel 1.0 py39h6e9494a_7
    - setuptools 67.7.2 pyhd8ed1ab_0
    - tk 8.6.12 h5dbffcc_0
    - tzdata 2023c h71feb2d_0
    - wheel 0.40.0 pyhd8ed1ab_0
    - xz 5.2.6 h775f41a_0
  run:
    - python >=3.9,<3.10.0a0
    - python_abi 3.9.* *_cp39
    - ruamel.yaml.clib >=0.1.2
    - setuptools
test:
  imports:
    - ruamel.yaml
about:
  home: https://sourceforge.net/p/ruamel-yaml
  license: MIT
  license_file: LICENSE
  summary: A YAML package for Python. It is a derivative of Kirill Simonov's PyYAML
    3.11 which supports YAML1.1
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - davidbrochart
    - jakirkham
    - mbargull
    - mwcraig
    - ocefpaf
    - pelson
    - xhochy
