# This file created by conda-build 3.25.0
# ------------------------------------------------

package:
  name: brotli-python
  version: 1.1.0
source:
  fn: brotli-1.1.0.tar.gz
  sha256: e720a6ca29428b803f4ad165371771f5398faba397edf6778837a18599ea13ff
  url: https://github.com/google/brotli/archive/v1.1.0.tar.gz
build:
  ignore_run_exports_from:
    - brotli
  number: 0
  string: py39h840bb9f_0
requirements:
  build:
    - bzip2 1.0.8 h0d85af4_4
    - c-ares 1.19.1 h0dc2134_0
    - ca-certificates 2023.7.22 h8857fd0_0
    - cctools_osx-64 973.0.1 habff3f6_14
    - clang 15.0.7 h694c41f_3
    - clang-15 15.0.7 default_hdb78580_3
    - clang_osx-64 15.0.7 h03d6864_3
    - clangxx 15.0.7 default_hdb78580_3
    - clangxx_osx-64 15.0.7 h2133e9c_3
    - cmake 3.27.4 hf40c264_4
    - compiler-rt 15.0.7 he1888fc_1
    - compiler-rt_osx-64 15.0.7 he1888fc_1
    - icu 73.2 hf5e326d_0
    - krb5 1.21.2 hb884880_0
    - ld64_osx-64 609 h0fd476b_14
    - libclang-cpp15 15.0.7 default_hdb78580_3
    - libcurl 8.2.1 h5f667d7_0
    - libcxx 16.0.6 hd57cbcb_0
    - libedit 3.1.20191231 h0678c8f_2
    - libev 4.33 haf1e3a3_1
    - libexpat 2.5.0 hf0c8a7f_1
    - libiconv 1.17 hac89ed1_0
    - libllvm15 15.0.7 he4b1e75_3
    - libnghttp2 1.52.0 he2ab024_0
    - libssh2 1.11.0 hd019ec5_0
    - libuv 1.46.0 h0c2f820_0
    - libxml2 2.11.5 h3346baf_1
    - libzlib 1.2.13 h8a1eda9_5
    - llvm-tools 15.0.7 he4b1e75_3
    - ncurses 6.4 hf0c8a7f_0
    - ninja 1.11.1 hb8565cd_0
    - openssl 3.1.2 h8a1eda9_0
    - rhash 1.4.4 h0dc2134_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.5 h829000d_0
  host:
    - brotli 1.1.0 h0dc2134_0
    - bzip2 1.0.8 h0d85af4_4
    - ca-certificates 2023.7.22 h8857fd0_0
    - libcxx 16.0.6 hd57cbcb_0
    - libffi 3.4.2 h0d85af4_5
    - libsqlite 3.43.0 h58db7d2_0
    - libzlib 1.2.13 h8a1eda9_5
    - ncurses 6.4 hf0c8a7f_0
    - openssl 3.1.2 h8a1eda9_0
    - pip 23.2.1 pyhd8ed1ab_0
    - python 3.9.18 h07e1443_0_cpython
    - readline 8.2 h9e318b2_1
    - setuptools 68.1.2 pyhd8ed1ab_0
    - tk 8.6.12 h5dbffcc_0
    - tzdata 2023c h71feb2d_0
    - wheel 0.41.2 pyhd8ed1ab_0
    - xz 5.2.6 h775f41a_0
  run:
    - libcxx >=15.0.7
    - python >=3.9,<3.10.0a0
    - python_abi 3.9.* *_cp39
  run_constrained:
    - libbrotlicommon 1.1.0 h0dc2134_0
test:
  imports:
    - brotli
about:
  home: http://github.com/google/brotli
  license: MIT
  license_file: LICENSE
  summary: Brotli compression format
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - CJ-Wright
    - wesm
    - xhochy
